name: KillionCommons
version: ${version}
main: co.killionrevival.killioncommons.KillionCommons
authors: [tut, flyerzrule, Fross, DecryptedX]
api-version: "1.21"
depend:
  - ProtocolLib
softdepend:
  - Essentials
  - Vault
