# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.5.0

      - name: Build Project
        id: build
        uses: KillionRevival/gradle-builder-action@v2
        with:
          token: ${{ secrets.PAT }}
          java-version: "21"

      - name: Upload Release Asset
        id: release
        uses: KillionRevival/release-action@v2
        with:
          jar-path: ${{ steps.build.outputs.jar-path }}

      - name: Deploy to package repo
        id: deploy
        uses: KillionRevival/gradle-deploy-action@v1
        with:
          java-version: "21"
